### ISSUE TITLE
pi freezes

### ISSUE THREAD

**Issue by mesw** [FDelporte/MinimalJavaFx11Application#1]
When I try this on my Pi 4 with a fresh raspbian installation, the pi freezes and can not be recovered without a hard reset (only mouse keeps active, no keyboard inputs accepted).
Tried with bell-sw jdk11 and 13

**Comment by FDelporte** [comment]
Since I wrote this example and the blog post, the default JDK has changed in Raspbian. I will try to update both post and this project soon.

**Comment by mesw** [comment]
I could not get it to run with the instructions from your book either, **yet**. At the moment I only have a pi 4 for testing, so the issue might be with the pi4.

**Comment by FDelporte** [comment]
you can always mail me more info on javaonraspberrypi@webtechie.be as I would be very interested to know what's going wrong, so if you would be able to give me access to your Pi (or to your PC with VNC to your Pi) through eg Teamviewer I could check what's going wrong

**Comment by mesw** [comment]
That is an awesome idea. I will just try it one more time with the full raspbian image, as I noticed, the standard image did not have AdoptOpenJDK11 included (there was no jdk at all installed). I will stick to the instructions from the book starting with the setup. If that does not work, we can do the remote session. I will send you an email once I am done trying, or let you know if I found the problem.

**Comment by mesw** [comment]
I gave it another try, but could not get javafx to show any sign of life. :(
Could it be a problem that I am using all the example code with the bell-sw jdk?

I took notes along the way, if you or somebody else can spot an error I would really be happy if I could get this to work soon. There is not a lot of documentation out there and I felt very lucky when I stumbled upon your book :+1: 
There seems to be something that I am missing, or there was some change in one of the dependencies that I missed.

- install full image (2.5GB) via imager
- boot
- set locale and language dialog
- set wifi dialog
- update software dialog (failed, because could not find repositories)
- reboot (dialog)
- sudo raspi-config
- set keyboard layout
- set vnc enabled
- set graphic memory 512mb
- update config tool
- sudo apt update
- sudo apt upgrade
- java -version -> openjdk 11.0.6
- sudo apt install maven
- git clone https://github.com/FDelporte/JavaOnRaspberryPi.git
- ./Chapter_04_Java/scripts/install_liberica_11.0.2.sh -> bell activated
- ./Chapter_07_JavaFX/scripts/gluonhq_add_archetypes.sh
- ./Chapter_07_JavaFX/scripts/gluonhq_create_empty_javafx_project.sh
- mvn javafx:run -> ERROR
- mvn -v -> 11.0.2-BellSoft,
- mvn clean package -> success
- change pom javafx-maven-plugin version to 0.0.4 instead of 0.0.1
- mvn javafx:run -> ERROR2 -> DEBUG1
- added Main-Class: be.webtechie.App in MANIFEST.MF and copied into jar file
- java -jar target/javafx-minimal-0.0.1.jar -> * failed to add service - already in use?
- sudo raspi-config and set fake opengl driver
- java -jar target/javafx-minimal-0.0.1.jar -> * failed to add service - already in use?
- sudo raspi-config and set gpu memory to 256MB
- java -jar target/javafx-minimal-0.0.1.jar -> * failed to add service - already in use?
- /boot/config.txt change to #dtoverlay=vc4-fkms-v3d
- java -jar target/javafx-minimal-0.0.1.jar ->
```

Udev: Failed to write to /sys/class/input/mice/uevent
      Check that you have permission to access input devices
Udev: Failed to write to /sys/class/input/mouse0/uevent
      Check that you have permission to access input devices
Udev: Failed to write to /sys/class/input/event0/uevent
      Check that you have permission to access input devices
Udev: Failed to write to /sys/class/input/input7/uevent
      Check that you have permission to access input devices
```

- sudo java -jar target/javafx-minimal-0.0.1.jar -> nothing is happening
- CRTL+ALT+F2 and login and kill x with sudo service lightdm stop
- sudo java -jar target/javafx-minimal-0.0.1.jar -> nothing is happening
- /boot/config.txt change to dtoverlay=vc4-fkms-v3d


After that I tried again with the jar file from this project, see notes below the detailed error messages that are referenced above.


____________________________________________
ERROR2:

```
* failed to add service - already in use?
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 
```

DEBUG1:


`[DEBUG] Executing command line: [java, --module-path, /home/pi/JavaOnRaspberryPi/javafx-minimal/target/classes:/home/pi/.m2/repository/org/openjfx/javafx-base/11.0.2/javafx-base-11.0.2-linux.jar:/home/pi/.m2/repository/org/openjfx/javafx-controls/11.0.2/javafx-controls-11.0.2-linux.jar:/home/pi/.m2/repository/org/openjfx/javafx-graphics/11.0.2/javafx-graphics-11.0.2-linux.jar, --add-modules, be.webtechie, -classpath, /home/pi/JavaOnRaspberryPi/javafx-minimal/target/classes:/home/pi/.m2/repository/org/openjfx/javafx-base/11.0.2/javafx-base-11.0.2.jar:/home/pi/.m2/repository/org/openjfx/javafx-controls/11.0.2/javafx-controls-11.0.2.jar:/home/pi/.m2/repository/org/openjfx/javafx-graphics/11.0.2/javafx-graphics-11.0.2.jar, --module, be.webtechie/be.webtechie.App]`


ERROR1:

```

[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.openjfx.JavaFXRunMojo.executeCommandLine (JavaFXRunMojo.java:525)
    at org.openjfx.JavaFXRunMojo.executeCommandLine (JavaFXRunMojo.java:487)
    at org.openjfx.JavaFXRunMojo.execute (JavaFXRunMojo.java:168)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.openjfx.JavaFXRunMojo.executeCommandLine(JavaFXRunMojo.java:525)
	at org.openjfx.JavaFXRunMojo.executeCommandLine(JavaFXRunMojo.java:487)
	at org.openjfx.JavaFXRunMojo.execute(JavaFXRunMojo.java:168)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```
_______________________________________________________



- git clone https://github.com/FDelporte/MinimalJavaFx11Application.git

```
sudo java \
       --module-path /opt/armv6hf-sdk/lib \
       --add-modules=javafx.controls \
       -jar ../out/MinimalJavaFx11Application-0.1-SNAPSHOT.jar
```
   -> * failed to add service - already in use?
```
sudo java \
       -jar ../out/MinimalJavaFx11Application-0.1-SNAPSHOT.jar
```
   -> * failed to add service - already in use?

- /boot/config.txt change to "#dtoverlay=vc4-fkms-v3d" from "dtoverlay=vc4-fkms-v3d" (and reboot of course)

```
sudo java \
        -jar ../out/MinimalJavaFx11Application-0.1-SNAPSHOT.jar
```
    -> nothing happens, waiting in shell
```
sudo java \
       --module-path /opt/armv6hf-sdk/lib \
       --add-modules=javafx.controls \
       -jar ../out/MinimalJavaFx11Application-0.1-SNAPSHOT.jar
```
    -> nothing happens, waiting in shell


I would gladly take you up on that offer with a shared remote session, if that offer still stands.

I could not reproduce the freezing of the pi, that is the topic of this ticket.

**Comment by mesw** [comment]
After trying [this](https://bell-sw.com/announcements/2019/09/12/JDK-JavaFX-Video-Preview/) tutorial, there was a javafx window on my screen. I am so happy now :smile: 
The problem in your book examples and this minimal example seems to be connected to maven javafx plugin or some other maven related problem. Maven seems to download some other javafx and not use the libericaFX. Because building with javac directly and launching with java worked right away with LibericaJDK-13. :relieved: 
Could it be that for this example to work, the Gluon JavaFX has to be used?

**Comment by FDelporte** [comment]
Thanks for the feedback! Will investigate and update both example and book.
I assume problem is on Pi4 as I validated everything on Pi3B+.
